### ISSUE TITLE
... functions expecting arrays

### ISSUE THREAD

**Issue by vurvdev** [lolleko/gmod-typescript#1]
Functions like ``print`` are generated as so right now:
```ts
declare function print(args: any[]): void;
```

They *should* be like this instead (as far as I know)
Works for me when I manually changed it.
```ts
declare function print(...args: any[]): void;
```

~~Nice project dude, I was thinking of making this but then was pointed to this after they found it when I somehow couldn't..~~

Another Note: I think you're supposed to make all of these functions ``@noSelf`` because they're all passing nil as the first argument. https://typescripttolua.github.io/docs/the-self-parameter/

**Comment by vurvdev** [comment]
Yeah, adding ``/** @noSelfInFile **/`` under ``/// <reference path="./extras.d.ts" />`` fixed nil being the first argument passed to every single function. I could PR this stuff myself but it'd take time.

**Comment by lolleko** [comment]
Hey, thanks for the issue. I recently upgraded the generator to use the new gmod wiki and the types still need some tweaking.

I will have a look, at fixing vararg and adding noselfinfile next week!

**Comment by lolleko** [comment]
@Vurv78 I published https://www.npmjs.com/package/gmod-types please let me know if that works for you. You are welcome to join our discord if you have further questions https://discord.gg/BWAq58Y

**Comment by vurvdev** [comment]
@lolleko Yep, works perfectly, thanks 👍
