### ISSUE TITLE
Entity classes (Like Player/Npc/Weapon) should extend the Entity class

### ISSUE THREAD

**Issue by vurvdev** [lolleko/gmod-typescript#3]
If you try and access an Entity function on a Player, you'll get an error. Same with trying to compare a Player with an Entity. This is since these classes don't derive / extend the ``Entity``.

In my bindings for Haxe to starfall I ended up hardcoding these since the Gmod Wiki doesn't tell you anything about which classes inherit from what
https://github.com/Vurv78/SFHaxe/blob/528b30a2a78ac5f044aac5d8583c67da84f05955/src/generator/Hardwired.hx#L39

Will probably need to do the same here unfortunately, there's some basic/the most common ones in the link I provided

**Comment by lolleko** [comment]
Added in 0.2.0
Added `extends entity` to the following entity derived classes: https://github.com/lolleko/gmod-typescript/blob/master/generator/transformer/modifications.json#L2
If anything is missing, please let me know.
