### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by itz-coffee** [lolleko/gmod-typescript#4]
Would it be possible to support optional arguments? An example of this would be https://wiki.facepunch.com/gmod/Global.EmitSound
```ts
declare function EmitSound(soundName: string, position: Vector, entity: number, channel: CHAN, volume: number, soundLevel: SNDLVL, soundFlags: SND, pitch: number, dsp: number): void;
```
When it should be:
```ts
declare function EmitSound(soundName: string, position: Vector, entity: number, channel?: CHAN, volume?: number, soundLevel?: SNDLVL, soundFlags?: SND, pitch?: number, dsp?: number): void;
```

**Comment by lolleko** [comment]
Added optionals in `gmod-types@0.2.0`.
Also, added limited support for default arguments when possible. (see #6 for limitations)

Let me know if you encounter any problems.
