### ISSUE TITLE
Realms info are lost in the declarations

### ISSUE THREAD

**Issue by TIMONz1535** [lolleko/gmod-typescript#9]
Information about realm of methods is lost in the declarations comments. Can you generate it automatically, right?

I mean:
![изображение](https://user-images.githubusercontent.com/7351599/150699816-6e10ab4c-926a-43d6-b9bf-f5d3121f6af7.png)

One plugin make a feature for drawing "realm" squares :)
https://marketplace.visualstudio.com/items?itemName=venner.vscode-glua-enhanced
![изображение](https://user-images.githubusercontent.com/7351599/150700460-e057e3cb-dce9-4eb4-a19e-65c37f694903.png)

Of course, it is enough just to write realm at the beginning of the method comment.
![изображение](https://user-images.githubusercontent.com/7351599/150700943-7b373e8b-402c-45ff-b217-0754369dcdbc.png)

https://wiki.facepunch.com/gmod/States
`Server`
`Client`
`Shared`
`Menu`
`Server and Menu`
`Client and Menu`
`Shared and Menu`

**Comment by lolleko** [comment]
I actually scrape  this information from the wiki, so it should be fairly easy for me to add it to the documentation string. I am not sure about the coloured squares. I want the declarations to be compatible with every editor, so I will probably just use [Client] [Server] ....

**Comment by lolleko** [comment]
Added in v0.3.0
